
[sncast.devnet]
account = "EmmanuelToken"
accounts-file = "/home/emmanex/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = " http://127.0.0.1:5050"

[sncast.sepolia-account]
account = "sepolia-account"
accounts-file = "/home/emmanex/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050"
